# Generated by Django 6.0.2 on 2026-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
