# Generated by Django 6.0.2 on 2026-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('motivation', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
