# Generated by Django 6.0.2 on 2026-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_note_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
